env:
  browser: true
  es2021: true

extends:
  - "airbnb-base"
  # - "plugin:jest/recommended"

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

ignorePatterns: [/dist/*, /node_modules/*]

rules:
  no-console: 0
  import/extensions: 0
